(define (square-tree tree)
    (map (lambda (sub-tree) 
                 (if (pair? sub-tree)
                        (square-tree sub-tree)
                        (* sub-tree sub-tree)))
         tree))
(square-tree (list (list 1 2) (list 3 4)))